// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtR4IsduwCxnibBipCtuBEovl8ifnj-XI',
    appId: '1:333975996524:web:3b0836870491f698407049',
    messagingSenderId: '333975996524',
    projectId: 'railway-de499',
    authDomain: 'railway-de499.firebaseapp.com',
    storageBucket: 'railway-de499.firebasestorage.app',
    measurementId: 'G-KKFP66KM42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUyd2shsMCrzayc0fgdxJYtn_7AfFL7ac',
    appId: '1:333975996524:android:b325d3c1a5efd940407049',
    messagingSenderId: '333975996524',
    projectId: 'railway-de499',
    storageBucket: 'railway-de499.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4JEDaTQitHKK8zSYxerzEwWBlx6MrxfM',
    appId: '1:333975996524:ios:43c3f06c412f1fca407049',
    messagingSenderId: '333975996524',
    projectId: 'railway-de499',
    storageBucket: 'railway-de499.firebasestorage.app',
    iosBundleId: 'com.example.railmind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4JEDaTQitHKK8zSYxerzEwWBlx6MrxfM',
    appId: '1:333975996524:ios:43c3f06c412f1fca407049',
    messagingSenderId: '333975996524',
    projectId: 'railway-de499',
    storageBucket: 'railway-de499.firebasestorage.app',
    iosBundleId: 'com.example.railmind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtR4IsduwCxnibBipCtuBEovl8ifnj-XI',
    appId: '1:333975996524:web:1bfb78c6a97ebbcc407049',
    messagingSenderId: '333975996524',
    projectId: 'railway-de499',
    authDomain: 'railway-de499.firebaseapp.com',
    storageBucket: 'railway-de499.firebasestorage.app',
    measurementId: 'G-CNNJEZ2L9V',
  );
}
